name: ci

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    types: [opened, synchronize, reopened, closed]

jobs:
  build:
    if: |
      github.event_name == 'push' ||
      (github.event_name == 'pull_request' && github.event.pull_request.merged == true)
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    env:
      AWS_REGION: ap-northeast-1
      SOURCE_BUCKET: ci-source-buildtest-kobashi
      CODEBUILD_PROJECT: deploy-readme-s3
      ROLE_TO_ASSUME: arn:aws:iam::312556765073:role/GitHubActionsRole-buildtest-kobashi

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Trivy fs scan
        uses: aquasecurity/trivy-action@0.20.0
        with:
          scan-type: fs
          ignore-unfixed: true
          format: table
          exit-code: '1'
          severity: 'CRITICAL,HIGH'

      - name: Prepare source.zip
        run: |
          mkdir bundle
          cp README.md bundle/
          (cd bundle && zip -r ../source.zip .)

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: ${{ env.ROLE_TO_ASSUME }}

      - name: Upload source.zip to S3
        run: aws s3 cp source.zip s3://${{ env.SOURCE_BUCKET }}/source.zip

      - name: Start CodeBuild
        run: aws codebuild start-build --project-name "${{ env.CODEBUILD_PROJECT }}"
