name: advisory-scan-demo

on:
  pull_request:
    branches: ['*']

jobs:
  pr-scan:
    name: Security Scan (advisory)
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Fake vulnerability scan (always fail)
        run: |
          echo "Running fake vulnerability scan (demo)..."
          echo "::group::Findings"
          echo "::error title=Trivy(HIGH)::CVE-0000-0000 in package xyz (fake)"
          echo "::error title=Gitleaks::Potential secret in .env (fake)"
          echo "::endgroup::"
          echo "## Advisory Security Report" >> $GITHUB_STEP_SUMMARY
          echo "- Trivy: 1 HIGH (fake)" >> $GITHUB_STEP_SUMMARY
          echo "- Gitleaks: 1 potential secret (fake)" >> $GITHUB_STEP_SUMMARY
          sleep 5  # 進行中の見た目を少し作る
          exit 1   # 常に失敗＝赤バツ
